# generate_server_and_task_parameters.py
# Utility script to generate:
# 1) Server configuration Excel files (homogeneous / heterogeneous) with 3 sheets per file (low/med/high)
# 2) Task parameters Excel file (task_parameters.xlsx) based on taskQueue.json

import pandas as pd
import random
from configuration import parameters
import numpy as np
import json
from scipy.stats import truncnorm

# Number of cloud servers is fixed in the project configuration
NUM_CLOUD_SERVERS = parameters.NUM_CLOUD_SERVERS


def generate_processing_frequencies(number_of_server, server_type):
    """Generate processing frequencies for edge or cloud servers.
    - For 'edge': sample from EDGE_PROCESSING_FREQ_RANGE
    - For 'cloud': sample from CLOUD_PROCESSING_FREQ_RANGE
    """
    if server_type == "edge":
        # Edge server processing frequency list
        return [round(random.uniform(*parameters.EDGE_PROCESSING_FREQ_RANGE), 2) for _ in range(number_of_server)]
    else:
        # Cloud server processing frequency list
        return [round(random.uniform(*parameters.CLOUD_PROCESSING_FREQ_RANGE), 2) for _ in range(number_of_server)]


def load_rsu_data(json_filename="graph_data.json"):
    """Load RSU data from the JSON file produced by GraphNetwork.save_graph().
    Returns:
        dict: rsus dictionary, e.g., { "RSU_0": {"position": [...], "range": ..., "edge_server_numbers": ...}, ... }
    """
    with open(json_filename, 'r') as f:
        data = json.load(f)
    return data['rsus']  # Extract RSU data as a dictionary


def load_task_queue(json_filename="taskQueue.json"):
    """Load task queue data from taskQueue.json generated by GraphNetwork.generate_Task_Queue().
    Returns:
        list: each item includes vehicle_id, time, interarrival_time
    """
    with open(json_filename, 'r') as f:
        return json.load(f)  # Return list of tasks


def generate_server_info_per_state(scenario_type, filename, rsu_data):
    """
    Generate server info Excel with exactly 3 sheets:
      {Scenario}_state_low, {Scenario}_state_high, {Scenario}_state_med

    Each sheet columns:
      Server_ID, Server_Type, Processing_Frequency, Failure_Rate, RSU_ID

    Notes:
    - Server_ID is a sequential counter across edge servers and then cloud servers (per sheet).
    - Failure rates are sampled from scenario/state-specific intervals computed in configuration.parameters.
    """
    # Get failure-rate intervals (edge/cloud x homogeneous/heterogeneous x low/med/high)
    failure_rates = parameters.compute_failure_rates()

    # Sheet/state order used in this file
    state_types = ["low", "high", "med"]

    for state_type in state_types:
        # Reset the ID counter for each sheet/state
        server_counter = 1
        server_info = []

        # Output schema for each sheet
        columns = ['Server_ID', 'Server_Type', 'Processing_Frequency', 'Failure_Rate', 'RSU_ID']

        # -------- Edge servers (per RSU) --------
        for rsu_id, rsu_info in rsu_data.items():
            # Number of edge servers attached to this RSU (from graph_data.json)
            num_edge_servers = rsu_info['edge_server_numbers']

            # Random processing frequencies for this RSU's edge servers
            edge_frequencies = generate_processing_frequencies(num_edge_servers, "edge")

            for i in range(num_edge_servers):
                server_id = server_counter
                server_type = "Edge"
                processing_frequency = edge_frequencies[i]

                # Choose failure-rate interval based on scenario_type (homogeneous vs heterogeneous) and state_type
                failure_rate_interval = (
                    failure_rates['edge']['homogeneous'][state_type]
                    if scenario_type == "homogeneous"
                    else failure_rates['edge']['heterogeneous'][state_type]
                )

                # Sample a failure rate from the interval
                failure_rate = round(random.uniform(*failure_rate_interval), 6)

                # RSU_ID is the RSU that hosts this edge server
                row = [server_id, server_type, processing_frequency, failure_rate, rsu_id]
                server_info.append(row)
                server_counter += 1

        # -------- Cloud servers (global pool) --------
        cloud_frequencies = generate_processing_frequencies(NUM_CLOUD_SERVERS, "cloud")
        for i in range(NUM_CLOUD_SERVERS):
            server_id = server_counter
            server_type = "Cloud"
            processing_frequency = cloud_frequencies[i]

            # Choose cloud failure-rate interval based on scenario_type and state_type
            failure_rate_interval = (
                failure_rates['cloud']['homogeneous'][state_type]
                if scenario_type == "homogeneous"
                else failure_rates['cloud']['heterogeneous'][state_type]
            )

            # Sample a failure rate from the interval
            failure_rate = round(random.uniform(*failure_rate_interval), 6)

            # RSU_ID is set to "cloud" for cloud servers (not attached to a specific RSU)
            row = [server_id, server_type, processing_frequency, failure_rate, "cloud"]
            server_info.append(row)
            server_counter += 1

        # Convert to DataFrame for writing
        server_df = pd.DataFrame(server_info, columns=columns)

        # Sheet naming convention used by the rest of the project (EnvState/params)
        sheet_name = f'{scenario_type.capitalize()}_state_{state_type}'

        # Write mode:
        # - First sheet uses 'w' (create/overwrite file)
        # - Next sheets use 'a' (append more sheets)
        mode = 'w' if state_type == state_types[0] else 'a'
        with pd.ExcelWriter(filename, engine='openpyxl', mode=mode) as writer:
            server_df.to_excel(writer, sheet_name=sheet_name, index=False)


def generate_task_params(json_task_queue="taskQueue.json"):
    """Generate task parameters and save them to task_parameters.xlsx.

    - Reads task schedule from taskQueue.json
    - Samples:
        * Task_Size from TASK_SIZE_RANGE (integer)
        * Computation_Demand from a truncated normal distribution
          bounded by [Low_demand, High_demand]
    - Writes one row per task with:
        Task_ID, Vehicle_ID, Time, Interarrival_Time, Task_Size, Computation_Demand
    """
    task_queue = load_task_queue(json_task_queue)
    task_info = []

    # Task size range and computation demand bounds from configuration
    TASK_SIZE_RANGE = parameters.TASK_SIZE_RANGE
    a, b = parameters.Low_demand, parameters.High_demand

    # Truncated normal parameters:
    # - mean at midpoint
    # - sigma chosen so that [a,b] spans ~6 sigmas (approx)
    mu = (a + b) / 2
    sigma = (b - a) / 6
    lower, upper = (a - mu) / sigma, (b - mu) / sigma

    # Build the task table in the same order as taskQueue entries
    for task_id, task in enumerate(task_queue, start=1):
        # Random task size (integer)
        task_size = np.random.randint(*TASK_SIZE_RANGE)

        # Computation demand sampled from truncated normal distribution
        computation_demand = truncnorm.rvs(lower, upper, loc=mu, scale=sigma)

        task_info.append({
            "Task_ID": task_id,
            "Vehicle_ID": task['vehicle_id'],
            "Time": task['time'],
            "Interarrival_Time": task['interarrival_time'],
            "Task_Size": task_size,
            "Computation_Demand": computation_demand
        })

    # Save to Excel used by MainLoop/Task creation
    task_df = pd.DataFrame(task_info)
    task_df.to_excel('task_parameters.xlsx', index=False)


def main():
    # Load RSUs from graph_data.json (generated by GraphNetwork.save_graph)
    rsu_data = load_rsu_data()

    # Generate server info for both scenario types (each with 3 state sheets)
    generate_server_info_per_state('homogeneous', 'homogeneous_server_info.xlsx', rsu_data)
    generate_server_info_per_state('heterogeneous', 'heterogeneous_server_info.xlsx', rsu_data)

    # Generate task parameters Excel file from taskQueue.json
    generate_task_params()

    print("Parameters defined in Excel files!")
