# project_main.py
# Entry point for running simulation experiments across scenario types and failure states.

import sys
import os
import shutil

# Allow imports from the parent directory (project root / module resolution)
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from params import params
from mainLoop import MainLoop


# Run a single simulation run (MainLoop handles episodes internally)
def run_simulation():
    ml = MainLoop()
    ml.EP()


def _get_scenario_and_p():
    """
    Determine the active scenario name and its probability parameter p.

    Supported scenarios:
      - base             => p = 0.0
      - trajectory_noise => p = params.trajectory_noise_p
      - missing_data     => p = params.missing_data_p

    Returns:
        scenario_folder (str): folder name used under results directory
        p (float): scenario probability parameter used in naming outputs
    """
    scenario = getattr(params, "scenario", "base")

    if scenario == "trajectory_noise":
        p = getattr(params, "trajectory_noise_p", 0.0)
        scenario_folder = "trajectory_noise"
    elif scenario == "missing_data":
        p = getattr(params, "missing_data_p", 0.0)
        scenario_folder = "missing_data"
    else:
        # base
        p = 0.0
        scenario_folder = "base"

    return scenario_folder, p


def clear_results_folders():
    """
    Clean existing results for the currently selected (scenario, model_tag) before running.

    - Deletes rsu_behavior_log.csv if it exists
    - Computes scenario folder and model tag
    - Prompts before deleting matching results subfolders under:
        heterogeneous_results/<scenario>/<model_tag>
        homogeneous_results/<scenario>/<model_tag>
    """

    # Optional local log file cleanup (if generated by the simulation)
    if os.path.exists("rsu_behavior_log.csv"):
        print("Removing rsu_behavior_log.csv")
        os.remove("rsu_behavior_log.csv")

    scenario_folder, p = _get_scenario_and_p()

    # Model tag: includes model_summary + optional "_flat" + scenario probability p
    # Replace '.' with '_' to keep folder names clean on all OSes
    flat_suffix = "_flat" if getattr(params, "Flat_mode", False) else ""
    model_tag = f"{params.model_summary}{flat_suffix}_{p:.2f}".replace(".", "_")

    # Both scenario types share the same subfolder scheme
    folder = params.SCENARIO_TYPE
   
    # Target subfolder path: <scenario_type_results>/<scenario>/<model_tag>
    subfolder = os.path.join(folder, scenario_folder, model_tag)

    # Only attempt deletion if the folder exists
    if os.path.exists(subfolder) and os.path.isdir(subfolder):
        print(f"Folder detected: {subfolder}")
        ans = input(f"Are you sure you want to DELETE this folder and all contents? (y/n): ")

        if ans.lower() == "y":
            shutil.rmtree(subfolder)
            print(f"Folder {subfolder} removed.")
        else:
            print(f"Skipped deleting {subfolder}.")
    else:
        print(f"Folder {subfolder} does not exist, skipping.")


def main():
    """
    Experiment driver:
    - Clears old results for the active scenario/model
    - Sets params accordingly (including alpha values)
    - Runs the simulation
    """

    clear_results_folders()

    # which scenario types to run (e.g., heterogeneous vs homogeneous)
    scenario_type = params.SCENARIO_TYPE # "heterogeneous" , "homogeneous"
    # which failure states to run (e.g., low / med / high)
    failure_state = params.FAILURE_STATE  # example: ["low", "med", "high"]
    print(f"#####   Running simulation for {scenario_type} scenario, state {failure_state}  #######")
    # Configure failure-rate scaling (alpha) based on scenario type and failure state
    params.alpha_edge = params.Alpha['edge'][scenario_type][failure_state]
    params.alpha_cloud = params.Alpha['cloud'][scenario_type][failure_state]
    # Run simulation for the current setting
    run_simulation()


# Standard Python entry point
if __name__ == "__main__":
    main()
